# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/wangzhao/booksim2/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/wangzhao/booksim2/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/wangzhao/booksim2/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/wangzhao/code/MAERI_VERILOG/mkDN_DistributionNetwork.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_DistributionSwitch.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_DistributionSwitch_Controller.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_DistributionSwitch_NIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_EgressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_IngressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_SubTree.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_SubTree_Controller.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_SubTree_EgressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkDN_SubTree_IngressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkMN_MultiplierNetwork.v
  /home/wangzhao/code/MAERI_VERILOG/mkMN_MultiplierSwitch.v
  /home/wangzhao/code/MAERI_VERILOG/mkMN_MultiplierSwitch_Controller.v
  /home/wangzhao/code/MAERI_VERILOG/mkMN_MultiplierSwitch_NIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_CollectionBus.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_DblReductionSwitch.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_DblReductionSwitch_Controller.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_DblReductionSwitch_Datapath.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_DblReductionSwitch_EgressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_DblReductionSwitch_IngressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_ReductionNetwork.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_SglReductionSwitch.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_SglReductionSwitch_Controller.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_SglReductionSwitch_Datapath.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_SglReductionSwitch_EgressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkRN_SglReductionSwitch_IngressNIC.v
  /home/wangzhao/code/MAERI_VERILOG/mkSC_INT16Adder.v
  /home/wangzhao/code/MAERI_VERILOG/mkSC_INT16Multiplier.v
  /home/wangzhao/code/MAERI_VERILOG/mkMAERI_Accelerator.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mkMAERI_Accelerator -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mkMAERI_Accelerator.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mkMAERI_Accelerator_utilization_synth.rpt -pb mkMAERI_Accelerator_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
